OutfitSales/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>22</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
</CustomObject>

OutfitSales/src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <label>Carts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OutfitSales/src/classes/SignUpAccountController.cls
public class SignUpAccountController {

     public Account account {get;set;}
     public Cart__c cart{get;set;}
     public String email{get;set;}
     public String name{get;set;}
     public String password{get;set;}
     public String phone{get;set;}
    
    
    public PageReference Save() {
    try{
        Account account=new Account();
        Cart__c cart=new Cart__c();
        account.Email__c=email;
        account.name=name;
        account.Password__c=password;
        account.phone=phone;
        insert account;
        cart.Account__c= account.Id;
        insert cart;
        
        return page.OutfitLoginPage;
        }
   catch(Exception ex){
          System.debug('Exception In SignUpAccountController'+ex.getMessage());
          ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Required Field Missing'));
          return null;
        }         
    }


    public PageReference Cancel() {
        return page.OutfitLoginPage;
    }


    

   
    
}